version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  app:
    image: python:3.10
    container_name: python_app
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://root:example@mongodb:27017/"
    volumes:
      - .:/app
    working_dir: /app
    command: ["bash", "-c", "pip install -r requirements.txt && python main.py"]

volumes:
  mongo_data:
