version: '3'
services:
  postgres_host:
    image: postgres:12
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
    
